# Generated by Django 2.2.5 on 2019-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionalinformation',
            name='country',
            field=models.CharField(choices=[('US', '美国'), ('CA', '加拿大'), ('MX', '墨西哥'), ('GB', '英国'), ('DE', '德国'), ('FR', '法国'), ('IT', '意大利'), ('ES', '西班牙'), ('JP', '日本')], default='美国', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conventionalinformation',
            name='store_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
